alias ls="ls -G"
alias l="ls"
alias ll="ls -hl"
alias la="ls -ah"
alias lla="ls -ahl"
alias lt="ls -t"
alias lr="ls -rt"
alias v="vim"
alias o="open"
alias macvim='o -a MacVim'
alias m="make"

# git related alias
alias gita='git add'
alias gitb='git branch'
alias gitc='git commit -a -m'
alias gitd='git diff'
alias gitf='git fetch'
alias gitm='git merge'
alias gito='git checkout'
alias gitp='git push'
alias gitr='git rebase'
alias gits='git status'
alias gitt='git tag'
alias gitu='git pull'
alias gitamend='git commit --amend -a'
alias gitsub='git submodule'
alias gitsup='git submodule update'
alias gitl2='git log --graph --decorate --pretty=format:"%C(yellow)%h %C(blue)(%ar) %C(green)<%cn> %C(red)%d %Creset%s"'
alias gitl='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias gg='gitl'
alias g='gg --all'
alias ggg='gitl2 --all'
# list conflicts
alias gitlc="git diff --name-only --diff-filter=U"

export EDITOR="vim"
export SVN_EDITOR="vim"
# export PS1="\u@\h: \W $ "
export PS1="\h:\w $ "

export PATH=$HOME/bin:$HOME/bin/apache-maven-3.2.5/bin:$PATH

